### ISSUE TITLE
Submitting Proposal

### ISSUE THREAD

**Issue by ev1stensberg** [tc39/agendas#182]
# Got a proposal for a feature

 Where do I submit, and what do I submit? Can assist with detailed a detailed walk-through of the feature, if you require so.

Thanks!

**Comment by ljharb** [comment]
@ev1stensberg See https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md for information about proposals.

**Comment by ev1stensberg** [comment]
Thanks, submitted on Es-discuss. Here's the [link](https://esdiscuss.org/topic/new-assignment-operators-not-bit-wise-or) :facepunch:
