### ISSUE TITLE
Question regarding the three dots punctuator in ECMA-262

### ISSUE THREAD

**Issue by patrickcharollais** [tc39/agendas#242]
Good day TC39 members,

May I kindly ask you to answer to Mr. Andrew Li (see his message below) ?

Thanks in advance and all the best from a sunny Geneva.

Patrick

From: ecmainte@web-wb-12.dfinet.ch [mailto:ecmainte@web-wb-12.dfinet.ch] 
Sent: mercredi 5 juillet 2017 04:40
To: Patrick Charollais <patrick@ecma-international.org>
Subject: A question regarding ECMA-262

I had a question about the ECMA-262 Standard, which is the language specification for ECMAScript, specifically about the 6th edition and later. Would the ... (three dots) punctuator, denoting the spread of elements, be referred to as an 'operator' or 'syntax'. Is it more correct to refer to the feature as 'the spread operator' or 'spread syntax'? 

Andrew Li 
- 
United States - 

Reply to: ***********@gmail.com

**Comment by ljharb** [comment]
@patrickcharollais this is a public repo; I think you may have meant to post this to the reflector?

I've edited to remove the person's personal info.

**Comment by ljharb** [comment]
Separately; please request they ask directly to the [es-discuss](esdiscuss.org) mailing list.

**Comment by littledan** [comment]
To answer the question, `...` is commonly known as the spread operator.

Generally, it'd be nice if we could avoid Patrick getting the overhead of receiving and forwarding these emails, and direct people to es-discuss or GitHub more readily. @patrickcharollais , Do you know why these people are contacting you with questions, rather than reaching out to those forums?

**Comment by Li357** [comment]
I'm feeling a bit stupid now, I had completely forgotten TC39 had public repos, that should have been my go-to. I'll look into discussing on the email list, and be more aware next time.
