### ISSUE TITLE
Proposal: freeze the agenda in the second Friday before meetings

### ISSUE THREAD

**Issue by leobalter** [tc39/agendas#258]
This a process proposal that shouldn't be effective for the meeting of 2017-09.

Freezing the agenda in the second-to-last Friday before the meetings might be helpful. Things to consider in this case:

- Friday could be considered within each one's timezone, regardless of location.
- This still provides others a full week, Monday to Friday, to review items before the meeting, regardless of timezone/location and the time required for traveling.
- We can allow some flexibility for items added a bit late. A Friday night commit in the Pacific time wouldn't affect the available week days to review the work.
- It gives us some extra few days compared to the current policy.

If we are positive with this change, we should have this explicitly set as a policy for the next agendas.

**Comment by ljharb** [comment]
This would extend the current consensus of "7 days prior" to roughly 10 days prior?

That seems reasonable to me; it should be a quick consensus to obtain during this meeting.

One concern, however, is that would deprive me of a full weekend - the time when I suspect most of us have free to work on proposals - to get something ready for the meeting.

**Comment by leobalter** [comment]
roughly 10.

> One concern, however, is that would deprive me of a full weekend - the time when I suspect most of us have free to work on proposals - to get something ready for the meeting.

Out of almost 2 months of time to make plans for the next meetings, yes. This affects me in the same way as my work for proposals is also done in my "open source time" (read weekends). I believe it's a fair trade-off still.

btw, I just missed the deadline to give updates on Float16 for this reason.

**Comment by domenic** [comment]
I would prefer a hard deadline in UTC instead of the "some time on Friday" this thread seems to be promoting. That's when I know it's safe to look at the agenda. Even if that time is "23:59 on Friday in UTC-12".

**Comment by leobalter** [comment]
that's fine. I discussed this with the Rex and @littledan in the chair meeting to confirm we're on the same page.

To make sure this is well known we should inform everyone on Tuesday in the meeting. I should update this on top of #259.
