### ISSUE TITLE
tc39-proposal-class-constructor-abbreviation-master

### ISSUE THREAD

**Issue by patrickcharollais** [tc39/agendas#265]
Good day TC39 members,

Please find attached a contribution received from a developer (Mr. Matej Minarik  - matejminarik.fiit@gmail.com) via the Ecma International web form"TC39 Royalty Free 3rd party contribution request".

Thanks in advance for taking care of it and best regards.

Patrick Charollais

**Comment by ljharb** [comment]
@patrickcharollais hi Patrick! There's no attachment here; however, please post things like this to the reflector first, and not a public repo.

**Comment by michaelficarra** [comment]
I've removed the email address from @patrickcharollais's comment to protect the submitter's privacy.
