### ISSUE TITLE
new requirement: proposals looking for stage 4 must include PR link?

### ISSUE THREAD

**Issue by michaelficarra** [tc39/agendas#311]
We've had a few cases of champions bringing stage 3 proposals, looking for stage 4, without the PR reviewed by the editor, as required by our process. Requiring the PR link might help champions to not forget this step.

**Comment by domenic** [comment]
In my case it was that I forgot an affirmative review was required; I remembered the PR requirement at least. I'm curious if there's anything we could do to help my mistake as well.

**Comment by littledan** [comment]
Sounds like a good practice. Requirement is a bit of a harsh word--we already have a requirement in the process document. It's a good practice to link to slides in the agenda, but we don't require it in the agenda.

**Comment by ljharb** [comment]
I also forgot to do so until my turn to present came up :-/

**Comment by michaelficarra** [comment]
You don't think anyone would have warned you before the meeting that you were missing the required PR link?

**Comment by ljharb** [comment]
That certainly would have helped! I think it's a good requirement.

**Comment by mathiasbynens** [comment]
In the past, we've advanced proposals to stage 4 _pending editor sign-off on the PR_. This seems like a good enough solution to me; it seems kind of obvious that the editors have to agree with the specifics in the actual PR before merging it, at which point it officially reaches stage 4.

**Comment by ljharb** [comment]
Since it seems that everyone (including three of us on this thread) forgot to include the PR link on our "seeking stage 4" agenda items, I've gone ahead and added them in 
3d05480f7d51b252413322fc9bec48e893c81828.

**Comment by mathiasbynens** [comment]
I didn’t forget — there is no such requirement yet! In my case, the PRs are listed in the linked materials (slides).

**Comment by ljharb** [comment]
Ha, fair enough :-)

**Comment by chicoxyzzy** [comment]
Seems like this issue could be closed now.

**Comment by littledan** [comment]
To be honest, I think slides are often a more useful resource for more of the committee than the PR to merge the proposal, and I hope the editors are keeping tabs on all the PRs against the main spec, but I'm fine with including all the links in the agenda as well.
