### ISSUE TITLE
Clarification on Internet media type and standard file names

### ISSUE THREAD

**Issue by patrickcharollais** [tc39/agendas#322]
Good day TC39 members,

Please find forwarded below a clarification request.

Many thanks in advance.

Patrick

From: ecmainte@web-wb-12.dfinet.ch [mailto:ecmainte@web-wb-12.dfinet.ch] 
Sent: vendredi 23 février 2018 15:12
To: Patrick Charollais <patrick@ecma-international.org>
Subject: Clarification on Internet media type and standard file names

Hello. I would appreciate some clarification on the status of the internet media type "application/ecmascript" and its association with "es" file extension. My hope is that this internet media type is already an officially recognised standard and already has an official association with the aforementioned file extension. Could you confirm that these standards are already in place and govern the above specification, and if so, could you please link me to them? I have made a similar request to the ISO for clarification of the same as I am finding it difficult to determine the status of the matter while researching it. It need not be said that there is legacy confusion with the popular historic name of the language, "JavaScript", thus the ambiguity. My hope is to use this information as a counter-argument against the emerging standard of using "mjs" as a file extensions for module files in NodeJS. It appears that the "mjs" file type is also semi-officially known as the "Michael Jackson Script" file extension. I need not say more. Thanks for your time. David.

**Comment by devsnek** [comment]
RFC 4329 specifies application/javascript and application/ecmascript

mjs is on its way, you can follow this email thread if you like https://www.ietf.org/mail-archive/web/json/current/msg04202.html

**Comment by bmeck** [comment]
Note that the document @devsnek linked above does add the `goal=` parameter to disambiguate different parsing goals of ECMA262. The document above also reflects that `application/javascript` to be supported but OBSOLETE to realign with [Web Browser Standards](https://html.spec.whatwg.org/multipage/scripting.html#scriptingLanguages).

**Comment by objectkit** [comment]
@bmeck 
Thank you for pointing out [Web Browser Standards](https://html.spec.whatwg.org/multipage/scripting.html#scriptingLanguages)

@devsnek Thank you for clarification on [application/ecmascript](https://tools.ietf.org/html/rfc4329#section-8.2)

From reading through quickly, I believe I understand the rationale behind the inclusion of the `m` prefix as an identifier to demarcate to vendors that hosts will be interpreting file contents with the expectation of ES6+ modules, and that makes sense. If I wanted to suggest a joint standard such that the `es` file type will also suffice as an equivalent identifier, how would one go about that? I understand it would not be straightforward, but I would find it desirable. Feedback appreciated.

**Comment by bmeck** [comment]
@objectkit you would submit a new internet draft to the IETF which controls the MIME like https://github.com/bmeck/I-D/tree/master/javascript-mjs and submit through IETF tools at https://datatracker.ietf.org/submit/

**Comment by objectkit** [comment]
@bmeck Very much appreciated.

I may take an independent punt at submitting a new draft based on the one that you have already produced.

If I were to proceed with doing so, it would bear respect to and encompass accreditation of your draft with your permission. 

It would specify that ``mjs`` and ``es`` are intersubstitutable, yet prioritise ``es`` as it is not a [TLA](https://en.wikipedia.org/wiki/Three-letter_acronym). The express motive of doing so is to silence my own overbearing impersonal desire for simplicity as a bedrock for the languages dynamism.

I am open to any countenances of course, so please continue to post comments as necessary.

Namaste

**Comment by ljharb** [comment]
This seems answered; closing.

**Comment by domenic** [comment]
I would suggest not trying to push `es` on the community via a standards process, as it has very little use, and per the inventor of the language ["ECMAScript was always an unwanted trade name that sounds like a skin disease."](https://en.wikipedia.org/wiki/ECMAScript#History).

**Comment by objectkit** [comment]
I hear you @domenic. I do know it is not going to be easy considering that sociocultural normativity and historic business identities seem to override concerns for the brevity of the file extension I have a fixation with possibly proposing. It is unfortunate that you quote a reference to skin disease considering the plight of Michael Jackson for example. Such concerns should not apply here. Logical brevity should, at least in my opinion. I appreciate your feedback however!

**Comment by snuggs** [comment]
@objectkit  that's been my entire point for years now as people sit back and laugh. As an African American with skin issues I'm actually shocked seeing this rhetoric saying "Michael Jackson Script" is ok but "ECMAscript" sounds like a skin disease. quoted or not....NOT COOL @domenic. You're usually the watchdog for this type of rhetoric. You are better than that. Quite disappointed. And offended. 😦 

You may want to revisit the [WHATWG CoC](https://whatwg.org/code-of-conduct)

**Comment by mikesamuel** [comment]
@snuggs, @objectkit,
I agree in part.  "Michael Jackson Script" communicates nothing of value and can offend.
Jokes are not a good way to frame the relative merits of `.mjs` and `.es`.

But I don't think it's fair to blame @domenic for what seems like a coincidence.
Domenic didn't raise "Michael Jackson Script" in this thread, and per "skin disease" was actually quoting Brendan who, IIUC, compared "ECMA" with "Eczema" long before anyone proposed the `.mjs` extension.

That said, I don't see Brendan's point about the marketing value of "ECMA-" as a point against `.es`.  JavaScript/EcmaScript, whatever you want to call it, has already won in the marketplace for client-side languages, so we wouldn't miss any marketing opportunity by going with `.es`.

**Comment by gesa** [comment]
Hey @snuggs, I'm on the Code of Conduct committee and just wanted to let you know we saw your message. You're right that the comment Brendan made back in 2006 was hurtful and has no place in the discourse now. Thank you for pointing it out. We'll be encouraging the entire technical committee to avoid this wording in the future.
