### ISSUE TITLE
How should we schedule the "JS classes 1.1" proposal?

### ISSUE THREAD

**Issue by littledan** [tc39/agendas#338]
This proposal is pretty cross-cutting, and intersects with several other proposals, including decorators and static public fields. Should we schedule it earlier within the hour timebox section? Also, should we allocate more than an hour to it? I'd be worried about putting it in the non-timeboxed section, though, as that could lead it to fall off the bottom of the agenda.

**Comment by littledan** [comment]
cc @zenparsing @allenwb @bterlson

**Comment by allenwb** [comment]
I think it would make sense to have in earlier in the week so attendee have a chance to think and talk about it over the course of the meeting.  I would also give it 1 hour, but let the chair judge whether there is a productive discussion that should be allowed to spill over a bit.

The actual time is going to have to be based on @BrendanEich 's schedule, as he will be presenting.  From a purely personal sleep loose minimization perspective, I'd prefer late afternoon London time.  I believe that next week we are still in the window where the US west coast is -7 hours relative to London.

**Comment by leobalter** [comment]
I’m joining the meeting remotely. If you schedule any time different than
the ordinary from the meetings, please let me know. Even if it’s for a pre
discussion or anything.

**Comment by littledan** [comment]
>  I would also give it 1 hour, but let the chair judge whether there is a productive discussion that should be allowed to spill over a bit.

So far, we have gotten strong pushback from committee members such as @ljharb for having the chairs decide things like this; that is why I'm asking the committee. I suppose we can ask the committee again at the time.

**Comment by erights** [comment]
This topic is both cross cutting and core to our mission. I recommend we start early and expect to spend lots of time on it --- much more than one hour. I'm sure we will anyway.

**Comment by littledan** [comment]
OK, for now, I moved the JS classes 1.1 discussion above my own 1-hour items. I'm wonder if we should ask the committee at the beginning of the meeting something like whether it'd be OK to give a half-hour introduction on the first day, just to begin discussing it, including in breaks, and then we can continue discussing it during the later hour-long timebox.

@BrendanEich , what is your schedule looking like?
