### ISSUE TITLE
sorting proposal-based agenda items primarily by current stage

### ISSUE THREAD

**Issue by michaelficarra** [tc39/agendas#360]
What do people think about having a proposal-based agenda items section which is primarily sorted by proposal stage in descending order, then secondarily sorted by timebox? I vaguely recall briefly discussing this at a recent meeting.

**Comment by ljharb** [comment]
Would the goal be to prioritize later-stage proposals?

The non-timeboxed sections already have this, somewhat, in that the order is "advancement", "new proposals", and "updates".

I can see the value in effectively having multiple timeboxes, where each one represents a category like that.

**Comment by michaelficarra** [comment]
Something like this:

## Agenda items

1. Opening, welcome and roll call
    1. Opening of the meeting (Mr. Jaeschke)
    1. TC39 follows its [Code of Conduct](https://tc39.github.io/code-of-conduct/)
    1. Introduction of attendees
    1. Host facilities, local logistics
    1. Quick recap of meeting IPR policy (Daniel Ehrenberg)
    1. Overview of communication tools (Brian Terlson)
1. Find volunteers for note taking
1. Adoption of the agenda
1. Approval of the minutes from last meeting
1. Next meeting host and logistics
1. Report from the Ecma Secretariat (15m)
1. Project Editors’ Reports
    1. ECMA262 Status Updates (15m)
    1. ECMA402 Status Updates (15m)
    1. ECMA404 Status Updates (15m)
    1. Test262 Status Updates (15m)
1. Updates from the CoC Committee (15m)
1. Web compatibility issues / Needs Consensus PRs

    | timebox | topic | presenter |
    |:-------:|-------|-----------|
    | 15m     | [Normative: Cleanup Time Values and Time Range](https://github.com/tc39/ecma262/pull/1144) Needs Consensus PR | Andrew Paprocki |
    | 15m     | [Normative: Add `export * as ns from "mod”` to Export production and Module Semantics](https://github.com/tc39/ecma262/pull/1174) | Valerie Young, John-David Dalton |

1. Overflow from previous meeting

    | timebox | topic | presenter |
    |:-------:|-------|-----------|

1. Discussions

    | timebox | topic | presenter |
    |:-------:|-------|-----------|
    | 15m     | 2019/2020 meeting scheduling update | Daniel Ehrenberg |
    | 30m     | Intl update ([slides](https://docs.google.com/presentation/d/1wEkpdxC37t4sk64QThcna8c4753-9Ak1I23LNDmZ9KE/edit?usp=sharing)) | ? |
    | 60m     | Stopping exfiltration ([Massive privacy violations](https://freedom-to-tinker.com/2018/01/12/website-operators-are-in-the-dark-about-privacy-violations-by-third-party-scripts/) vs [boundaries](https://twitter.com/BrendanEich/status/987349792505253888)) | Mark S. Miller |

1. Proposals

    | stage | timebox | topic | presenter |
    |:-----:|:-------:|-------|-----------|
    | 3     | 15m     | [Optional catch binding](https://tc39.github.io/proposal-optional-catch-binding/) for stage 4 ([#1185](https://github.com/tc39/ecma262/pull/1185)) | Michael Ficarra |
    | 3     | 30m     | [Numeric separators update](https://docs.google.com/presentation/d/1ivYa55mNEDPZ2z5K41fU5gwRxmlb4aUTrA0qEuBTfow/edit#slide=id.p) | Sam Goto, Rick Waldron, Leo Balter, Dan Ehrenberg |
    | 3     | 30m     | Updates and [a question to resolve](https://github.com/tc39/proposal-string-matchall/issues/34) on String.prototype.matchAll | Jordan Harband |
    | 3     | 30m     | BigInt status update at Stage 3 ([slides](https://docs.google.com/presentation/d/1Bx13eCgM9Rujs4zNdfO95de_4wehhx8RxNx5aZl-3D4/edit?usp=sharing), [repository](http://github.com/tc39/proposal-bigint/)) | Daniel Ehrenberg |
    | 3     | 30m     | Class fields status update at Stage 3 ([slides](https://docs.google.com/presentation/d/1oDQOS9b8wnuP5-o8zInsEO9lpRbhduawAmvfRzbxkOs/edit?usp=sharing), [repository](https://github.com/tc39/proposal-class-fields)) | Daniel Ehrenberg |
    | 3     | 30m     | [Function.prototype.toString revision](https://github.com/tc39/Function-prototype-toString-revision) updates ([slides](https://docs.google.com/presentation/d/1W3Qlhb76BNP5_DHLDRP-KvWq0qJpzoz8zL_1U_4YYSQ/edit?usp=sharing)) and stage 4 ([#697](https://github.com/tc39/ecma262/pull/697)) | Michael Ficarra |
    | 3     | 45m     | Approving a replacement name for Array.prototype.flatten (not smoosh) | Michael Ficarra |
    | 2     | 30m     | [Symbol.prototype.description](https://github.com/tc39/proposal-Symbol-description) for stage 3 | Michael Ficarra |
    | 2     | 60m     | Static class features for Stage 3 ([slides](), [repository](http://github.com/tc39/proposal-static-class-features/)) | Shu-yu Guo, Daniel Ehrenberg |
    | 2     | 60m     | Decorators for Stage 3 ([slides](https://docs.google.com/presentation/d/1sQJunzPUqaD-fbyGCRHJI1Sn5w2mo5F8hXFXfJOFTxY/edit?usp=sharing), [repository](https://github.com/tc39/proposal-decorators)) | Daniel Ehrenberg, Yehuda Katz, Brian Terlson |
    | 1     | 30m     | [Object.fromEntries](https://github.com/tc39/proposal-object-from-entries) to [stage 2](https://github.com/tc39/proposal-object-from-entries/issues/14)? | Jordan Harband, Kevin Gibbons |
    | 1     | 30m     | [Top-Level Await](http://github.com/mylesborins/proposal-top-level-await/) for stage 2 | Myles Borins |
    | --    | 15m     | [Sequence properties in Unicode property escapes](https://github.com/mathiasbynens/proposal-regexp-unicode-sequence-properties) for Stage 1 | Mathias Bynens |
    | --    | 15m     | [`as` destructuring patterns](https://github.com/zkat/proposal-as-patterns) for Stage 1 | Kat Marchán |
    | --    | 30m     | [Module Keys](https://github.com/mikesamuel/tc39-module-keys) for Stage 1 | Mike Samuel |
    | --    | 30m     | [Well-formed `JSON.stringify`](https://github.com/gibson042/ecma262-proposal-well-formed-stringify) for Stage 1 | Mathias Bynens |
    | --    | 60m     | Pattern Matching for Stage 1 ([github](https://github.com/tc39/proposal-pattern-matching)) | Kat Marchán, Brian Terlson |

1. Overflow from timeboxed discussion items (in insertion order)

    | topic | presenter |
    |-------|-----------|

1. Other business
    1. Thank host
1. Adjournment

**Comment by ljharb** [comment]
Seems reasonable - let's get consensus on it in May.

**Comment by michaelficarra** [comment]
For future agendas of course.

**Comment by littledan** [comment]
Huge fan of the table layout. Makes the whole thing more readable. Minor suggestion: Add an extra column for "done" rather than crossing out the row (makes it easier to read old agendas).

What's the motivation for putting "discussions" at the top? I think meeting planning needs priority, but I'm not sure if all discussions do. For example, I was considering adding an open-ended discussion topic about what our way forward is in general about syntactic proposals, and how to analyze "cross-cutting concerns". However, I don't want this to be prioritized and push out other proposals.

Idea for discussions: Short discussions go at the top, long discussions go at the bottom.

**Comment by michaelficarra** [comment]
@littledan Updated to split the long and short discussions. I think a "done" column would be a bit heavyweight. Maybe just mark them with a symbol in the topic or timebox field?

**Comment by michaelficarra** [comment]
@littledan It's a decent amount of work, and I'd rather not do it unless we're pretty sure that it'd be accepted. Let's get some more feedback first.
