### ISSUE TITLE
How should we prioritize revisiting Function.prototype.toString() censorship

### ISSUE THREAD

**Issue by littledan** [tc39/agendas#391]
This proposal is at a bit of an ambiguous state, whether it reached consensus to advance to Stage 2 or not. Would it be worth prioritizing revisiting it for 15 minutes ahead of some of the Stage 0/discussion topics? I'm not sure if we'll get to all of these. OTOH it wouldn't be the end of the world to consider a retraction at the next meeting. cc @domenic

**Comment by ljharb** [comment]
It makes a lot of sense to me to touch on it before stage 0 items.

Advancing to stage 2 is a public signal that a feature *definitely* will go into the language (according to the information available at the time) and downgrading back to stage 1 seems worse than letting it stay at stage 1 for 2 months imo (but it would be ideal to address it this week)
