### ISSUE TITLE
 Reviewing the future JS syntax throughout the current proposals (slides) 	Leo Balter

### ISSUE THREAD

**Issue by Ginden** [tc39/agendas#396]
"slides" link in [07.md](https://github.com/tc39/agendas/blob/master/2018/07.md) points to tc39/agendas repository.

@leobalter

**Comment by ljharb** [comment]
Resolved by #422.

**Comment by littledan** [comment]
I wouldn't mind if the slides actually do get posted. cc @leobalter

**Comment by leobalter** [comment]
https://docs.google.com/presentation/d/179v41LMaEXDxaD-piSgYVi6btFJoNoeYVncXe0172GM
