### ISSUE TITLE
Scheduling May 2018's overflow agenda items

### ISSUE THREAD

**Issue by littledan** [tc39/agendas#397]
In the May 2018 TC39 meeting, we decided to prioritize later stage proposals and short discussions over longer discussions and earlier stage proposals. I still think this was a good idea, but now we have a bit of a backlog of proposal introductions and discussion topics from last meeting, which may be good to get back to in the July 2018 meeting.

I want to suggest a way to schedule these topics in a way which might help us get through everything while not pushing out the later stage proposals that we also need to discuss:
- For Stage 0/1 proposals, let's discuss them in a 10-minute lightning talk sessions, which are oriented towards presenting a proposal to the committee and seeking feedback on GitHub (suggestion from @kosamari ). We could reserve Thursday morning for these lightning talks.
- For discussion topics, let's discuss these Thursday afternoon. By the end of TC39 meetings, we're all a bit tired, so let's use this time to reflect and think at a broader level what we'd like to do next.

Thoughts?

**Comment by domenic** [comment]
I'm unsure what you're suggesting, but one interpretation of it is that my topics got pushed back from one meeting, and now are getting restricted to 10-minute lightning talks in the next meeting. That would mean I would need three meetings before getting the longer discussion I originally scheduled, which would be very frustrating.

Is that the proposal?

**Comment by michaelficarra** [comment]
@domenic Do you not agree with the strategy of prioritising later stage proposals over newer ones to reduce our number of active proposals? The fact that newer ones are getting pushed off the end of the agenda shows that we have too many in the pipeline given available resources (3 days/2 months). It will only be like this until we reach a manageable number of active proposals, at which point it reaches a natural equilibrium.

**Comment by domenic** [comment]
Yeah, I do not agree with that strategy; I think some consideration has to be given to people who want to present their own work, even if other peoples' older proposals have had a hard time advancing. It's a balance, certainly.

**Comment by michaelficarra** [comment]
I understand and empathise with those who have earlier stage proposals at this time. I think that the balance you're requesting is what Dan is suggesting. That will allow the champion to at least publicise their idea and solicit committee feedback through GitHub. Do you have an alternative idea?

**Comment by domenic** [comment]
I preferred the balance where your proposal already got deprioritized (regardless of how early you had it ready for the agenda) by placing it below higher-stage proposals at one meeting. But you did not get continually punished for all future meetings, and instead we allowed overflow items to go first as they always have.

**Comment by michaelficarra** [comment]
That won't actually allow us to make any progress on our active proposal count though. All that strategy does is push off every low priority agenda item by one meeting, leaving us in exactly the same state each meeting and ever increasing our active proposal count.

**Comment by domenic** [comment]
Yes. I think that's OK; some proposals and champions have taken a long time, and that shouldn't automatically give them priority over others. It's not a goal in and of itself to me to keep the proposal count low, versus balancing other considerations like allowing more than just the usual crowd to present.

**Comment by littledan** [comment]
How about this: We schedule the overflow new topics first, as usual, but we put *new, unqueued* proposals in a lightning talks section starting Thursday morning, so they have a chance to get some initial exposure without being entirely pushed out? The idea here would be to give a slice of the limited time to each of them to promote further collaboration outside of the meetings, even if the ideal would be an in-depth discussion in the committee about everything.

**Comment by leobalter** [comment]
I continue opposing to forced lighting talks. If the presenter needs more than 10 minutes to present and discuss new ideas, I’m up to never restrict them and interested to learn what needs to be addressed I such time.

Once again, I don’t want to see the meetings becoming a race where everyone competes to bring in their proposals. Rather, I prefer to keep a slow pace where each item is properly discussed, without a hurry, so everyone works together to improve the language design.

**Comment by littledan** [comment]
I think lots of important discussions happen outside of the TC39 meetings, but it's hard to make those happen without some exposure in the meetings. However, if you oppose this strongly, I'll drop the idea.

**Comment by michaelficarra** [comment]
I think that would be fine.

**Comment by domenic** [comment]
> One would be, order things as, Stage 0 lightning talks (for champions which request it), then discussion topics, then Stage 0 lengthier discussions.

Where do overflow topics go? (Including overflow stage 0 lengthier discussions.) As I've stated before, I think they should go first.

**Comment by michaelficarra** [comment]
@domenic As the committee grows and the active proposal list grows, so too will the overflows. Eventually, the agenda will be filled with nothing but topics which couldn't be covered in a previous meeting. And how do we prioritise those items? Prioritising overflow is unsustainable and gets us nowhere other than a mandatory 2-month waiting period on all agenda items.

**Comment by domenic** [comment]
I understand your position, as you have repeated it several times. I can only repeat my own position, which is that I think that's preferable to letting the same people continue to dominate the discussion with their same old topics.

**Comment by michaelficarra** [comment]
@domenic In my most recent comment, I asked how we would prioritise items *within* the overflow, since the entire agenda would be overflow. If the answer is according to the main prioritisation order, we only succeed in pushing off agenda items by at least one meeting. If the answer is FIFO, we should abandon any kind of prioritisation attempts.

**Comment by ljharb** [comment]
I think it’s a bit slippery slope to start forecasting an entire agenda of overflow items; both the number of items and the total length varies from month to month. If that stops being true, and if there’s a consistent trend in the upwards direction, then we can re-evaluate.

**Comment by littledan** [comment]
I agree with others here that, for now, we can keep overflow topics first, prioritized analogously to the rest of the agenda. We can deal with the issue of too many overflow topics when we come to it; so far, we tend to have just a few hours of overflow items at the end of meetings. I want to stay sensitive to the risk of permanently starving some topics from being discussed in meetings.

Any concerns about the following ordering?
1. Overflow topics from the previous meeting, ordered similarly to the following agenda
1. Proposals order by decreasing stage to Stage 1
1. Stage 0 lightning talks (for champions which opt into this group, aiming for Thursday mornings)
1. Discussion topics (aiming for Thursday afternoons)
1. Stage 0 longer discussions, sorted by increasing timebox

For my overflowed discussion topics, I'd like to sort them into the Thursday afternoon bucket, rather than coming first in the meeting, as I think we'll be more effective in discussing them as part of a period of reflection towards the end of the meeting. Would that be OK, for me to opt into those particular topics coming later in the meeting?

**Comment by ljharb** [comment]
I believe it’s always been considered ok for folks to opt in to their topics happening later; SGTM.

**Comment by ljharb** [comment]
Closed with #400.
