### ISSUE TITLE
Are tc39 meetings video recorded and aggregated in one location by anyone?

### ISSUE THREAD

**Issue by ChrisDillinger** [tc39/agendas#410]
If there is a better place to ask such a question, please let me know. 
I'd like to be able to listen to these talks as I'm not able to attend in person.
Searching around online yields some results that are portions of random talks or just about TC39 itself and not on actual TC39 meetings.

Regards,

**Comment by shannon** [comment]
@devsnek @ljharb I know this issue has been closed, but I'd like to ask if it would be possible to record meetings in the future. The notes are not always complete and it could be beneficial for everyone if members of the community could transcribe the meetings after the fact.

**Comment by leobalter** [comment]
the meetings are not public and might contain private concerns (security, etc), so recordings is out of the plans for now.

**Comment by shannon** [comment]
Ok thanks @leobalter.

**Comment by erights** [comment]
By prearrangement, we have given recorded presentations at tc39 meetings, where the recording included the Q/A, e.g., [Extremely Modular Distributed JavaScript](https://www.youtube.com/watch?v=9WdbTucMaRo&list=PLKr-mvz8uvUgybLg53lgXSeLOp4BiwvB2). There are other prepared presentations that I've given or co-given that I wish I had recorded. (For example, I re-gave [Stopping Exfiltration](https://www.youtube.com/watch?v=pig-sIS8_Wc&list=PLKr-mvz8uvUgybLg53lgXSeLOp4BiwvB2) to a different audience, but of course they asked very different questions.)

 I think when the presenter wants to give a recorded presentation, asks the attendees if anyone objects, and no one objects, that it would be very nice to have such recordings.

**Comment by doniyor2109** [comment]
It would be great to collect some of them into one YouTube channel
