### ISSUE TITLE
list an Ecma member for the June 2019 meeting host

### ISSUE THREAD

**Issue by michaelficarra** [tc39/agendas#536]
The current host listed for the June 2019 meeting is JSConf EU. As far as I'm aware, they are not an Ecma member. Is there an Ecma member who would be more appropriate to list there?

**Comment by ljharb** [comment]
cc @littledan / @gesa

**Comment by ecmageneva** [comment]
Good question. I am not sure if we had a meeting hosted not by an Ecma member or the Secretariat, maybe a meeting which was parallel to a JTC1 SC meeting... Anyway, but I also wonder if the JSConf EU has any role in the TC39 meeting, except that we have planned our meeting next to that conference both in location and time. Stripe is definitely fine.
Istvan

**Comment by littledan** [comment]
I'd be fine with listing this as Stripe at this point; @ecmageneva 's description of roles seems accurate.
