### ISSUE TITLE
update requirements for stage 0 and stage 1 on the agenda document

### ISSUE THREAD

**Issue by codehag** [tc39/agendas#722]
We have been finding it difficult to review proposals that have no materials. Sometimes this happens with stage 1 proposals, as there is no strict requirement that they have materials present before the 10 day deadline. It is pretty rare that a stage 1 proposal does not advance, so having materials present isn't as crucial as for later stages. However, if all we have to go by is a title, it is difficult to prepare for the meeting in advance, or have preliminary discussions with champions. This in the end results in a less productive discussion during plenary.

How do people feel about changing the stage 1 requirement in the agenda template to having a ready repo with the proposal written out in prose, and a clear problem statement? This can be generated from the proposal template. We can help newer members adjust though mentoring.

**Comment by syg** [comment]
Strong +1.

On mentoring: in the March 2020 meeting I plan to formally "charter" the incubation calls, which I think would be a good mentoring venue for newer members who might be unsure of what materials would be appropriate for each stage.

**Comment by ljharb** [comment]
Since this is just "a repo with some explanation", and not slides, this seems like it's documenting the primary convention we've already been following.

**Comment by rkirsling** [comment]
I too have wished this were already the case—let's make it happen!

**Comment by mathiasbynens** [comment]
Strong +1. Previously:

- https://github.com/tc39/process-document/issues/25
- https://github.com/tc39/process-document/issues/24

**Comment by ljharb** [comment]
Ah, thanks for the history - in that case perhaps a PR to the process document is the first step, and then updating the agenda to match would be perfunctory?

**Comment by mathiasbynens** [comment]
https://github.com/tc39/process-document/pull/26

**Comment by ljharb** [comment]
I've added this to the agenda, so we can get consensus on it next week: https://github.com/tc39/agendas/commit/205e270d7091df7b08af626ce12f04983e058113

**Comment by codehag** [comment]
I am not sure what we should do about stage 0. Can't remember the last time we had one?

**Comment by ljharb** [comment]
I don't think we need to worry about it as much; if someone puts a stage 0 item on the agenda, with no materials, and not seeking advancement, it would be reasonable imo for the chairs to reach out and require materials, to ensure that our plenary time is well-managed.

**Comment by aadamsx** [comment]
>  I plan to formally "charter" the incubation **calls**

Is there a line/link for us "regular folk" to watch/listen in on the meetings?

**Comment by aadamsx** [comment]
The pipeline [operator proposal](https://github.com/tc39/proposal-pipeline-operator) has not made the stage 2 requirement of describing the syntax and semantics using formal spec language in F# style for submission to the TC39 (stage 2 draft) this time, so when is the next meeting going to be so we can make sure to be ready?

**Comment by ljharb** [comment]
@aadamsx no, meetings are not open to public observation (nor is that question on topic for this issue) The meetings are every 2 months, as you can see listed on the [next agenda](https://github.com/tc39/agendas/blob/master/2020/03.md#dates-and-locations-of-future-meetings).

Since none of this is on topic for this issue, I'll hide all of those comments.
