### ISSUE TITLE
Open meeting initiative #1

### ISSUE THREAD

**Issue by aadamsx** [tc39/agendas#726]
Following up on the TC39 Open meeting initiative:  Is there a line/link for us "regular folk" to watch/listen in on the meetings?

**Comment by ljharb** [comment]
No, only the notes that are posted a few weeks after each meeting.

**Comment by aadamsx** [comment]
Why isn't the process more open?  Is there a reason for keep these meetings behind closed doors?

**Comment by michaelficarra** [comment]
@aadamsx TC39's process is open. See our discussion about our openness and the changes we have made to make it even more accessible in [the most recent meeting's notes](https://github.com/tc39/notes/blob/master/meetings/2020-02/february-4.md#process-changes-to-accommodate-us-members-and-us-delegates). You may want to just skip to [the conclusion](https://github.com/tc39/notes/blob/master/meetings/2020-02/february-4.md#conclusion). I encourage you to participate in our process by contributing on the [TC39 Discourse](http://es.discourse.group/) or in #tc39 on freenode. You can also join #tc39-delegates on freenode as an observer or browse [the publicly-available logs](https://freenode.logbot.info/tc39-delegates) of that channel on the web.

**Comment by aadamsx** [comment]
I’d say you closed this rather quickly. Gives the impression discussion is not welcomed. Also, it just encourages one to create a new issue and link. 

> No consensus on live-streaming meeting

Why in the world would a consensus be needed to start a live streaming?  As I’m sure you’re well aware, live streaming is commonplace in meetings such as this.  Why not be as transparent as possible?

**Comment by ljharb** [comment]
Consensus is required for everything. If a single delegate objects, it doesn't happen.

Not everyone is comfortable with their every word and inflection becoming open to misinterpretation by the entire world, subject to their emotions at the time they hear it.

**Comment by jridgewell** [comment]
> I’d say you closed this rather quickly.

I think the issue was adequately answered.  I'd really encourage you to listen to the IRC chats, there is always a lot of discussion happening there.

>  Gives the impression discussion is not welcomed.

We'd welcome discussion, on any of the [mentioned](https://github.com/tc39/agendas/issues/726#issuecomment-606150549) locations. Having a discussion on the agenda tracker is inappropriate.

> Why in the world would a consensus be needed to start live streaming the meetings?

There are also companies that don't approve of delegates (who are representing the companies) being recorded for every opinion. It could mistakenly be interpreted as the company's opinion.
