### ISSUE TITLE
Clarify the timezone

### ISSUE THREAD

**Issue by Jack-Works** [tc39/agendas#782]
> 10:00 to 15:00 CT on June 1st, 2020

What does it mean for CT? It's ambiguous for the term CST (I know it's North America Central Time Zone in this context), but it could mean:

```
Central Standard Time, North America's Central Time Zone: UTC-06:00
China Standard Time: UTC+08:00
Cuba Standard Time: UTC-04:00
Central Standard Time, Australia Central Time Zone: UTC+9:30
```

Another question, 10 CST, does it mean the daylight saving time or not?

Google: 
10:00 am Sunday, Central Time (CT) is **11:00 pm** Sunday, in UTC+8

Duckduckgo:
Midnight - **12:00 AM** +0800 (1 day after)
Convert Timezone: 10:00 AM CST (UTC-6) to +0800

It's confusing when I converting the time to my local timezone.

**Comment by jridgewell** [comment]
It's Chicago time, so UTC-05:00 currently. https://www.timeanddate.com/worldclock/usa/chicago

**Comment by ptomato** [comment]
Shameless plug for giving Temporal a try! Go to https://tc39.es/proposal-temporal/docs/, open a browser console, and run this :smile:
```js
startTime = Temporal.Absolute.from('2020-06-01T10:00-05:00[America/Chicago]')
startTime.inTimeZone(Temporal.now.timeZone()).toString()
```

**Comment by ljharb** [comment]
My typical approach (if you have google available) is to search for, for example, "monday 10am ct in china" and it reports "11 pm in Beijing".

**Comment by Jack-Works** [comment]
Yes I tried Google and Duckduckgo and they give me different answer. Maybe the DST

**Comment by robpalme** [comment]
Thanks for highlighting the ambiguity, @Jack-Works 

[@jridgewell is correct](https://github.com/tc39/agendas/issues/782#issuecomment-636583155) - this meeting is happening on Chicago time which is CDT/UTC-5.

**Comment by chicoxyzzy** [comment]
Node.js meetings have an awesome timezones section.
https://github.com/nodejs/modules/issues/510
Can we borrow this approach?
