### ISSUE TITLE
Attendee information url broken for 83rd meeting

### ISSUE THREAD

**Issue by ranamahmud** [tc39/agendas#998]
On the following page "Agenda for the 83rd meeting of Ecma TC39" 
[https://github.com/tc39/agendas/blob/master/2021/05.md](https://github.com/tc39/agendas/blob/master/2021/05.md)
the URL for
Attendee information: [https://github.com/tc39/Reflector/issues/367](https://github.com/tc39/Reflector/issues/367)
is broken.

**Comment by ryzokuken** [comment]
@ranamahmud it's not broken, it points to a private repository. TC39 meetings can be attended only by delegates of ECMA members, Invited Experts and certain "observers". If you belong to any of these three categories, please contact the chairs for access.

**Comment by ranamahmud** [comment]
Thanks for the information.
